require('@nomiclabs/hardhat-ethers');
require('hardhat-deploy');
require('./waffle-tests');
require('./solidity-coverage-skips');
require('./gas-reporter-skips');
require('./flatten-all');
require('./import-artifacts');
require('./solidity-docgen');
require('./output-config');
